/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HomeInfo: typeof import('./src/components/homeInfo.vue')['default']
    InputText: (typeof import('primevue/inputtext'))['default']
    Menubar: (typeof import('primevue/menubar'))['default']
    NavBar: typeof import('./src/components/navBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: (typeof import('primevue/selectbutton'))['default']
    Tag: (typeof import('primevue/tag'))['default']
  }
}
